[BISERVER-8774] ERROR [net.sf.ehcache.store.DiskStore] libloader-dataCache: Failed to write element to disk
The pentaho log keeps logging the following error:

2013-04-01 10:48:39,167 ERROR [net.sf.ehcache.store.DiskStore] libloader-dataCache: Failed to write element to disk 'ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@17188069, factoryParameters={}, parent=null}'. Initial cause was org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceData
java.io.NotSerializableException: org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceData
at java.io.ObjectOutputStream.writeObject0(Unknown Source)
(…)